name: CI

on: [push, pull_request]

jobs:

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - run: yarn install
      - run: npx semantic-release
